classify_query_task:
  description: >
    Analyze the incoming user query and uploaded content to determine the primary media type.
    Classify as one of: 'text', 'image', 'audio', 'video', or 'mixed'.
    Consider both the uploaded file type and the nature of the user's question.
    
    Input: {query_text}, {file_info}
    
    Provide classification with confidence score and reasoning.
  expected_output: >
    A classification result containing:
    - media_type: The primary media type detected
    - confidence: Confidence score (0-1)
    - reasoning: Brief explanation of classification decision
    - recommended_agent: Which specialist agent should handle this

process_document_task:
  description: >
    Process text documents, PDFs, or written content using document analysis tools.
    Extract key information, perform semantic search, and identify important concepts.
    
    Query: {query_text}
    File: {file_path}
    
    Use document processing capabilities to provide comprehensive analysis.
  expected_output: >
    Document analysis results including:
    - extracted_text: Key text content found
    - key_concepts: Important concepts identified
    - summary: Brief summary of content
    - semantic_matches: Relevant semantic search results
    - metadata: Document properties and statistics

process_image_task:
  description: >
    Analyze uploaded images using computer vision capabilities.
    Identify objects, extract text, analyze visual features, and provide detailed descriptions.
    
    Query: {query_text}
    Image: {file_path}
    
    Use image analysis tools for comprehensive visual content understanding.
  expected_output: >
    Image analysis results including:
    - objects_detected: List of identified objects with confidence scores
    - scene_description: Overall description of the image
    - text_extracted: Any text found in the image (OCR)
    - visual_features: Key visual characteristics
    - semantic_tags: Relevant semantic tags for indexing

process_video_task:
  description: >
    Process video files by extracting key frames, analyzing motion, and understanding content.
    Identify scenes, objects in motion, and temporal changes.
    
    Query: {query_text}
    Video: {file_path}
    
    Use video processing tools for temporal visual analysis.
  expected_output: >
    Video analysis results including:
    - key_frames: Important frames extracted with timestamps
    - scene_changes: Detected scene transitions
    - motion_analysis: Movement and activity detected
    - objects_tracked: Objects identified across frames
    - video_summary: Overall content summary

process_audio_task:
  description: >
    Process audio files through transcription, speaker identification, and audio analysis.
    Convert speech to text and analyze audio characteristics.
    
    Query: {query_text}
    Audio: {file_path}
    
    Use audio processing tools for comprehensive audio analysis.
  expected_output: >
    Audio analysis results including:
    - transcript: Full transcription of speech content
    - speakers: Identified speakers (if multiple)
    - audio_quality: Technical audio properties
    - key_phrases: Important phrases or keywords
    - sentiment: Emotional tone analysis
    - timestamps: Time-aligned transcription segments

synthesize_response_task:
  description: >
    Take the processed results from specialist agents and create a comprehensive,
    user-friendly response. Organize information clearly and highlight key insights.
    
    Original Query: {query_text}
    Processing Results: {agent_results}
    Media Type: {media_type}
    
    Create a well-structured response that directly addresses the user's question.
  expected_output: >
    A comprehensive response containing:
    - direct_answer: Direct response to user's query
    - key_insights: Most important findings
    - detailed_results: Organized detailed analysis
    - confidence_score: Overall confidence in results
    - additional_info: Any relevant supplementary information
    - processing_metadata: Information about how the query was processed